---
- name: install required packages
  yum:
    name:
      - git
      - gcc
    state: present

- name: create user to run app
  user:
    name: "{{ app_user }}"
    system: yes
    state: present
    create_home: no

- name: download app source code
  git:
    repo: https://github.com/express42/reddit
    dest: "{{ app_dir }}"
    version: monolith
  notify: restart reddit

- name: install ruby gems
  bundler:
    state: present
    chdir: "{{ app_dir }}"
    user_install: no
  notify: restart reddit

- name: set source code permissions
  file:
    path: "{{ app_dir }}"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    recurse: yes

- name: copy service file
  template:
    src: templates/reddit.service
    dest: /etc/systemd/system/reddit.service
  notify: restart reddit
...
