---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ Chart.Name }}
  labels:
    app: reddit
    component: {{ .Chart.Name }}
    release: {{ .Release.Name }}
spec:
  ports:
  - port: {{ .Values.service.externalPort }}
    protocol: TCP
    targetPort: {{ .Values.service.internalPort }}
  selector:
    app: reddit
    component: {{ .Chart.Name }}
    release: {{ .Release.Name }}
