# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.box_check_update = false

  config.vm.provider :virtualbox do |v|
    v.memory = 512
  end

  config.vm.define "dbserver" do |db|
    db.vm.hostname = "dbserver"
    db.vm.network :private_network, ip: "10.0.10.10"

    db.vm.provision "ansible" do |ansible|
      ansible.playbook = "db.yml"

      ansible.extra_vars = {
        "dynamic_hosts": "all"
      }
    end
  end

  config.vm.define "appserver" do |app|
    app.vm.hostname = "appserver"
    app.vm.network :private_network, ip: "10.0.10.20"

    app.vm.provision "shell", inline:
      "echo DATABASE_URL=10.0.10.10:27017 > /etc/default/reddit"

    app.vm.provision "ansible" do |ansible|
      ansible.playbook = "app.yml"

      ansible.extra_vars = {
        "dynamic_hosts": "all"
      }
    end
  end
end
