---
- name: install required packages
  yum:
    name:
      - git
      - gcc
    state: present

- name: create user to run app
  user:
    name: "{{ app_user }}"
    system: yes
    state: present
    create_home: yes

- name: create directory to run app
  file:
    path: "{{ app_dir }}"
    state: directory
    mode: 0770
    owner: "{{ app_user }}"
    group: "{{ app_user }}"

- name: download app source code
  git:
    repo: https://github.com/express42/reddit
    dest: "{{ app_dir }}"
    version: monolith
  become: yes
  become_user: "{{ app_user }}"
  tags:
    - deploy
  notify: restart reddit

- name: install ruby gems
  bundler:
    state: present
    chdir: "{{ app_dir }}"
  tags:
    - deploy
  notify: restart reddit

- name: copy environment file
  template:
    src: templates/etc/default/reddit.env
    dest: /etc/default/reddit.env
  notify: restart reddit

- name: copy service file
  template:
    src: templates/etc/systemd/system/reddit.service
    dest: /etc/systemd/system/reddit.service
  notify: restart reddit
...
