version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - reddit_backend
  ui:
    build: ./src/ui
    image: ${DOCKER_USER}/ui:${UI_VERSION}
    ports:
      - ${EXTERNAL_PORT}:9292/tcp
    networks:
      - reddit_frontend
  post:
    build: ./src/post-py
    image: ${DOCKER_USER}/post:${POST_VERSION}
    networks:
      - reddit_frontend
      - reddit_backend
  comment:
    build: ./src/comment
    image: ${DOCKER_USER}/comment:${COMMENT_VERSION}
    networks:
      - reddit_frontend
      - reddit_backend

volumes:
  post_db:

networks:
  reddit_frontend:
  reddit_backend:
