---
- name: install required packages
  yum:
    name:
      - git
      - gcc
    state: present

- name: create user to run app
  user:
    name: "{{ app_user }}"
    system: yes
    state: present
    create_home: no

- name: setup port redirect from {{ external_port }} to {{ app_port }}
  firewalld:
    rich_rule: rule family=ipv4 forward-port port={{ external_port }} protocol=tcp to-port={{ app_port }}
    zone: public
    permanent: yes
    immediate: yes
    state: enabled

- name: open external port {{ external_port }}
  firewalld:
    port: "{{ external_port }}/tcp"
    zone: public
    permanent: yes
    immediate: yes
    state: enabled

- name: download app source code
  git:
    repo: https://github.com/express42/reddit
    dest: "{{ app_dir }}"
    version: monolith

- name: install ruby gems
  bundler:
    state: present
    chdir: "{{ app_dir }}"

- name: set source code permissions
  file:
    path: "{{ app_dir }}"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    recurse: yes

- name: copy service file
  template:
    src: templates/reddit.service
    dest: /etc/systemd/system/reddit.service
...
